import { FormEvent, useEffect, useState } from 'react';
import { api, Proposal } from '../shared/api/client';
export function App(){
 const[health,setHealth]=useState('연결 확인 중');const[content,setContent]=useState('');const[proposal,setProposal]=useState<Proposal|null>(null);const[proposalId,setProposalId]=useState('');const[title,setTitle]=useState('');const[tags,setTags]=useState<Proposal['tagCandidates']>([]);const[tasks,setTasks]=useState<any[]>([]);const[graph,setGraph]=useState<any>({nodes:[]});const[applicationId,setApplicationId]=useState('');const[message,setMessage]=useState('메모를 입력해 주세요.');
 useEffect(()=>{fetch('/api/v1/health').then(r=>r.ok?r.json():Promise.reject()).then(()=>setHealth('서버 연결됨')).catch(()=>setHealth('서버 연결 필요'))},[]);
 const refresh=async()=>{setTasks(await api.tasks());setGraph(await api.graph())};
 const capture=async(e:FormEvent)=>{e.preventDefault();try{setMessage('원문 저장 중…');const memo=await api.createMemo(content);setMessage('Fake 분석 후보 생성 중…');const run=await api.analyze(memo.id,memo.currentRevision);const p=await api.proposal(run.proposalId);setProposal(p);setProposalId(run.proposalId);setTitle(p.suggestedTitle.value);setTags(p.tagCandidates);setMessage('후보를 수정하거나 승인하세요.')}catch{setMessage('저장 또는 분석에 실패했습니다.')}};
 const apply=async()=>{if(!proposal)return;const r=await api.apply(proposalId,proposal,title,tags);setApplicationId(r.applicationId);setProposal(null);setContent('');setMessage('승인한 항목만 적용했습니다.');await refresh()};
 const undo=async()=>{await api.undo(applicationId);setApplicationId('');setMessage('파생 항목만 되돌렸습니다. 원문은 보존됩니다.');await refresh()};
 return <main><header><span className="eyebrow">PERSONAL MEMO</span><h1>생각을 먼저 적으세요.</h1><p>정리는 승인한 뒤에만 적용됩니다.</p><span className="status">● {health}</span></header><section className="canvas" aria-label="그래프 홈">{graph.nodes.length===0?<div className="empty">승인된 메모와 태그가 여기에 표시됩니다.</div>:graph.nodes.map((n:any)=><div key={n.id} className={`node ${n.kind.toLowerCase()}`}>{n.kind==='MEMO'?'메모 · ':''}{n.label}</div>)}</section><section className="tasks"><h2>할 일</h2>{tasks.length===0?<p>승인된 할 일이 없습니다.</p>:tasks.map(t=><article key={t.id}><span>{t.title}</span><strong>{t.overdue?'기한 초과':t.status}</strong></article>)}{applicationId&&<button className="undo" onClick={undo}>마지막 적용 되돌리기</button>}</section>{proposal&&<section className="review"><span className="eyebrow">REVIEW REQUIRED</span><h2>적용 전 확인</h2><label>제목<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="chips">{tags.map((t,i)=><button key={t.canonicalName} onClick={()=>setTags(tags.filter((_,x)=>x!==i))}>{t.canonicalName} ×</button>)}</div>{proposal.dateCandidates[0]&&<p>날짜: {proposal.dateCandidates[0].surfaceText} → {proposal.dateCandidates[0].value} ({proposal.dateCandidates[0].precision})</p>}<button className="approve" onClick={apply}>선택 항목 승인</button><button className="reject" onClick={()=>setProposal(null)}>지금은 적용하지 않기</button></section>}<form className="capture" onSubmit={capture}><label htmlFor="memo">{message}</label><textarea id="memo" value={content} onChange={e=>setContent(e.target.value)} required placeholder="예: 11.25 OS과제 제출"/><button>원문 저장 후 분석</button></form></main>
}
