package local.personalmemo.analysis.domain;

public enum AmbiguityReason {
  LOW_TYPE_MARGIN,
  LOW_TAG_SIMILARITY,
  TAG_CONFLICT,
  NEW_TOPIC,
  MISSING_YEAR,
  MISSING_TIME,
  IMPRECISE_DATE,
  CONFLICTING_DATES,
  UNRESOLVED_REFERENCE,
  MISSING_ACTION,
  MISSING_OBJECT,
  MULTI_INTENT,
  CANDIDATE_LIMIT_EXCEEDED,
  LOCAL_CLOUD_CONFLICT
}
