spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true

app:
  auth:
    registration-enabled: false
    google:
      registration-enabled: false
