package local.personalmemo.analysis.application;
import tools.jackson.databind.*; import tools.jackson.databind.node.ObjectNode; import java.nio.charset.StandardCharsets; import java.security.*; import java.sql.Timestamp; import java.time.*; import java.util.*;
import local.personalmemo.analysis.api.AnalysisDtos.*; import local.personalmemo.analysis.domain.LocalAnalyzer; import local.personalmemo.common.DevIdentity; import local.personalmemo.memo.application.MemoService;
import org.springframework.jdbc.core.simple.JdbcClient; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class AnalysisService {
 private final JdbcClient db; private final DevIdentity identity; private final MemoService memos; private final LocalAnalyzer analyzer; private final ObjectMapper json;
 public AnalysisService(JdbcClient d,DevIdentity i,MemoService m,LocalAnalyzer a,ObjectMapper j){db=d;identity=i;memos=m;analyzer=a;json=j;}
 @Transactional public RunView start(UUID memoId,String key,Start req){var memo=memos.get(memoId);if(memo.currentRevision()!=req.memoRevision())throw new IllegalArgumentException("STALE_MEMO_REVISION");var run=UUID.randomUUID();var proposal=UUID.randomUUID();var instant=Instant.now();var now=Timestamp.from(instant);ObjectNode p=analyzer.analyze(memoId,req.memoRevision(),memo.content(),instant,"Asia/Seoul");db.sql("insert into analysis_runs(id,owner_id,memo_id,memo_revision,route,status,schema_version,analyzer_version,ambiguity_reasons,created_at,completed_at) values(:id,:o,:m,:r,'MOCK','REVIEW_REQUIRED','1','fake-v1',cast(:a as jsonb),:n,:n)").param("id",run).param("o",identity.ownerId()).param("m",memoId).param("r",req.memoRevision()).param("a",p.get("ambiguityReasons").toString()).param("n",now).update();db.sql("insert into analysis_proposals values(:id,:r,cast(:p as jsonb),:h,:n)").param("id",proposal).param("r",run).param("p",p.toString()).param("h",hash(p.toString())).param("n",now).update();return new RunView(run,memoId,req.memoRevision(),"REVIEW_REQUIRED",proposal);}
 public JsonNode proposal(UUID id){return db.sql("select p.proposal_json::text from analysis_proposals p join analysis_runs r on r.id=p.analysis_run_id where p.id=:id and r.owner_id=:o").param("id",id).param("o",identity.ownerId()).query(String.class).optional().map(this::tree).orElseThrow();}
 @Transactional public Map<String,Object> apply(UUID proposalId,String key,Apply req){var existing=db.sql("select id from analysis_applications where owner_id=:o and idempotency_key=:k").param("o",identity.ownerId()).param("k",key).query(UUID.class).optional();if(existing.isPresent())return result(existing.get());var row=db.sql("select r.memo_id,r.memo_revision,r.status from analysis_proposals p join analysis_runs r on r.id=p.analysis_run_id where p.id=:p and r.owner_id=:o for update").param("p",proposalId).param("o",identity.ownerId()).query((rs,n)->new Object[]{UUID.fromString(rs.getString(1)),rs.getInt(2),rs.getString(3)}).single();UUID memoId=(UUID)row[0];int rev=(int)row[1];if(rev!=req.expectedMemoRevision()||memos.get(memoId).currentRevision()!=rev||"STALE".equals(row[2]))throw new IllegalArgumentException("STALE_MEMO_REVISION");UUID app=UUID.randomUUID();var now=Timestamp.from(Instant.now());db.sql("insert into analysis_applications values(:id,:o,:p,:m,:r,:k,'APPLIED',cast(:s as jsonb),:n,null)").param("id",app).param("o",identity.ownerId()).param("p",proposalId).param("m",memoId).param("r",rev).param("k",key).param("s",write(req)).param("n",now).update();for(Item it:req.items()){UUID item=UUID.randomUUID();db.sql("insert into memo_items(id,owner_id,memo_id,memo_revision,application_id,kind,title,created_at) values(:id,:o,:m,:r,:a,:k,:t,:n)").param("id",item).param("o",identity.ownerId()).param("m",memoId).param("r",rev).param("a",app).param("k",it.kind()).param("t",it.title()).param("n",now).update();if("TASK".equals(it.kind())){Timestamp due=null;if(it.due()!=null&&it.due().value()!=null){var date=LocalDate.parse(it.due().value());due=Timestamp.from(date.plusDays(1).atStartOfDay(ZoneId.of(it.due().timeZone())).toInstant());}db.sql("insert into task_details(memo_item_id,status,due_at_utc,date_surface_text,date_precision,source_time_zone,time_was_explicit) values(:i,'TODO',:d,:s,:p,:z,:e)").param("i",item).param("d",due).param("s",it.due()==null?null:it.due().surfaceText()).param("p",it.due()==null?null:it.due().precision()).param("z",it.due()==null?null:it.due().timeZone()).param("e",it.due()!=null&&it.due().timeSpecified()).update();}for(Tag t:req.selectedTags()){UUID tag=t.existingTagId();if(tag==null){tag=UUID.randomUUID();String norm=t.newCanonicalName().strip().toLowerCase(Locale.ROOT);db.sql("insert into tags values(:id,:o,:n,:x,'ACTIVE',:at,:at,0)").param("id",tag).param("o",identity.ownerId()).param("n",t.newCanonicalName().strip()).param("x",norm).param("at",now).update();}db.sql("insert into item_tags values(:i,:t,:a,'USER',null,:n)").param("i",item).param("t",tag).param("a",app).param("n",now).update();}}
 db.sql("update analysis_runs set status='APPLIED' where id=(select analysis_run_id from analysis_proposals where id=:p)").param("p",proposalId).update();return result(app);}
 @Transactional public Map<String,Object> undo(UUID app,String key){int changed=db.sql("update analysis_applications set status='UNDONE',undone_at=:n where id=:a and owner_id=:o and status='APPLIED'").param("n",Timestamp.from(Instant.now())).param("a",app).param("o",identity.ownerId()).update();if(changed>0){db.sql("delete from item_tags where application_id=:a").param("a",app).update();db.sql("delete from task_details where memo_item_id in(select id from memo_items where application_id=:a)").param("a",app).update();db.sql("delete from memo_items where application_id=:a").param("a",app).update();}return Map.of("applicationId",app,"status","UNDONE");}
 private Map<String,Object> result(UUID app){return Map.of("applicationId",app,"status",db.sql("select status from analysis_applications where id=:a and owner_id=:o").param("a",app).param("o",identity.ownerId()).query(String.class).single());}
 private JsonNode tree(String s){try{return json.readTree(s);}catch(Exception e){throw new IllegalStateException(e);}} private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException(e);}} private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}

